quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:smhi-temp-map.db
quarkus.datasource.username=
quarkus.datasource.password=

quarkus.flyway.migrate-at-start=true

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-schema=false

quarkus.http.port=8080

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://127.0.0.1:3000
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=origin,accept,content-type,authorization,x-requested-with

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
